#!/bin/bash
set -ex

# conda installer
export PATH=/opt/conda/bin:$PATH
install=Miniconda3-4.7.12.1-Linux-x86_64.sh
curl -O https://repo.continuum.io/miniconda/$install
bash $install -b -p /opt/conda
rm $install

